# Generated by Django 5.1.7 on 2025-03-09 10:39

import exchange.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='instrument',
        ),
        migrations.AddField(
            model_name='instrument',
            name='max_quantity',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='instrument',
            name='min_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instrument',
            name='tick_size',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ticker',
            field=models.CharField(default='UNKNOWN', max_length=10, validators=[exchange.models.validate_ticker]),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, validators=[exchange.models.validate_ticker]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticker',
            field=models.CharField(max_length=10, validators=[exchange.models.validate_ticker]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ticker', 'status', 'direction', 'price'], name='exchange_or_ticker_6ca0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='exchange_or_user_id_bf3142_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ticker', 'timestamp'], name='exchange_tr_ticker_80ba89_idx'),
        ),
    ]
