# Generated by Django 5.1.7 on 2025-03-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_remove_transaction_instrument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='min_quantity',
        ),
    ]
